[add] additional meta tags for SEO
origranot/reduced.to pull request #219
Opened 2022-10-15 19:40 UTC by iSumitBanik

This PR provides the addition of extra meta tags that are responsible for the SEO.

Issue #212

2022-10-16 21:32 UTC, origranot requested changes
@iSumitBanik 
Hey, please fix the comments 💯

2022-10-16 21:32 UTC, origranot commented on frontend/src/components/router-head/router-head.tsx
>        <meta name="twitter:title" content="Qwik" />
Please remove those meta tags.

2022-10-16 21:32 UTC, origranot commented on frontend/src/components/router-head/router-head.tsx
> +
Please remove the theme-color meta tag

2022-10-17 15:47 UTC, iSumitBanik commented on frontend/src/components/router-head/router-head.tsx
> +
Done

2022-10-17 16:34 UTC, origranot commented
@iSumitBanik We already merged a PR regarding our SEO.

Thank you so much!

2022-10-17 16:34 UTC, closed without merging