Avoid shortening an already short url (#271)
origranot/reduced.to pull request #350
Opened 2022-12-28 15:09 UTC by xarielah

Hi @origranot 

Added the backend block for the already-shortened URLs.
You can check the code, I'm available on discord if you wanna change something.

As far as the frontend concern there is no special message for that error (there is in the backend), so it is still 'Invalid URL...' message on the frontend.

2022-12-28 23:43 UTC, origranot commented on backend/src/shortener/shortener.service.ts
> +    return  (/^(https?:\/\/)?(www\.)?reduced\.to(\/.*)?$/).test(shortUrl)
I would change the domain name to be dynamic from config service.

2022-12-28 23:47 UTC, origranot commented on backend/src/shortener/shortener.controller.ts
> +      if(isAlreadyShortened) throw new Error('The URL is already shortened by reduced.to')
I would write it like this, makes it more easy to understand.

```suggestion
    try {
      parsedUrl = new URL(body.originalUrl);

      // Checks if the URL is not already a reduced.
      if(this.shortenerService.isURLAlreadyShortend(body.originalUrl)) {
          throw new Error('The URL is already shortened by reduced.to')
      }

2022-12-28 23:48 UTC, origranot requested changes
@xarielah Thank you for the PR,
Please fix the changes..

2022-12-29 08:10 UTC, xarielah commented
@origranot Now its dynamicly based on supplied env-var pulled from Config Serivce. Last commit should be enough.
Thanks for the CRs!

2022-12-29 08:16 UTC, origranot requested changes
It's looks good. Just implement the changes 😃

2022-12-29 08:16 UTC, origranot commented on backend/src/shortener/shortener.service.ts
> +    private readonly configService: ConfigService
For type safety, use the config wrapper instead of the normal ConfigService. Use AppConfigService.

2022-12-29 08:16 UTC, origranot commented on backend/src/shortener/shortener.controller.ts
> +      // Checks if the URL is not already a reduced.
Fix the grammar, *is not already reduced.

2022-12-29 08:27 UTC, xarielah commented
@origranot Done 🚀🚀

2022-12-29 11:42 UTC, origranot approved these changes
Nice!

2022-12-29 11:43 UTC, merged