Logger has been moved and implemented as an internal lib
origranot/reduced.to pull request #449
Opened 2023-09-18 21:11 UTC by senderh55

Related to #445

2023-09-19 18:15 UTC, origranot requested changes
@senderh55  This looks great!

There is a small comment I added (I guess this line was added by mistake)
Also, please run lint and test in your own env to make sure the CI works.

2023-09-19 20:25 UTC, senderh55 commented on apps/backend/src/shortener/shortener.controller.spec.ts
> +import { reduce } from 'rxjs';
I added it by mistake

2023-09-19 20:41 UTC, senderh55 commented
Thanks for your feedback. I updated the path in .eslintrc in the logger and fixed the mistake in shortener.controller.spec.

2023-09-22 14:41 UTC, origranot commented
@senderh55 Great job!

I had to remove the buildable option from the logger.
Thank you for your contribution!

Closes https://github.com/origranot/reduced.to/issues/445

2023-09-22 14:41 UTC, merged