Feature/impove login seo #455
origranot/reduced.to pull request #472
Opened 2023-09-30 19:34 UTC by MOHIT-PANDEY215

#455 Fix: Improve SEO on login page.
![image](https://github.com/origranot/reduced.to/assets/59007557/a9fe1e14-398d-4003-9e5a-e966da342cc5)

2023-09-30 19:49 UTC, origranot commented on apps/frontend/src/routes/login/index.tsx
> +        'Login to your Reduced.to account to manage your links and QR-Codes.',
We are not managing QR-Codes in our system.
Change the description to be something like: "Login to your Reduced.to account to manage your shortened links"

2023-09-30 19:49 UTC, origranot requested changes
@MOHIT-PANDEY215 Looks good 🚀 

There is a small comment I left, would you mind resolve it?
Also, please run the formatter on your changes using: `npx nx format:write`

2023-09-30 20:12 UTC, MOHIT-PANDEY215 commented
@origranot Thank you for the comment. I have applied the changes.

2023-10-01 09:32 UTC, origranot commented
@MOHIT-PANDEY215 Hey,
can you please run the formatter on your changes?

2023-10-02 16:52 UTC, merged