Fixes : #480 Added Dark mode logo in Hero
origranot/reduced.to pull request #486
Opened 2023-10-04 16:26 UTC by siddharth9300

Fixes : #480 Added Dark mode logo in hero section by creating different logo for dark mode and light mode.

Dark Mode : 
![image](https://github.com/origranot/reduced.to/assets/83226178/f111315f-26a9-4aee-90f4-13ef3792e2c3)

Light mode : 
![image](https://github.com/origranot/reduced.to/assets/83226178/1b120a14-113d-4fa0-95dc-227e9546bc21)

2023-10-04 19:29 UTC, origranot commented
@siddharth9300 Can't we do all of it with the fill property, what do you think?

2023-10-05 16:27 UTC, siddharth9300 commented
> @siddharth9300 Can't we do all of it with the fill property, what do you think?

Yes we can i please check the latest changes.

2023-10-07 19:30 UTC, origranot commented
> > @siddharth9300 Can't we do all of it with the fill property, what do you think?
> 
> 
> 
> @origranot  Yes we can ,please check the latest changes. I have made changes and done it with the fill property.

I checked it. Can't we use the same svg logo and just pass the fill property? (instead of duplicate the svg code)

2023-10-08 18:40 UTC, siddharth9300 commented
@origranot Instead of using fill property I have used filter property. I have committed the changes.

2023-10-13 12:42 UTC, origranot commented
@siddharth9300 Hey, can you please run the formatter to fix the prettier issues?

2023-10-16 13:00 UTC, siddharth9300 commented
@origranot Done 👍

2023-10-16 18:31 UTC, origranot requested changes
@siddharth9300 Great job!
I added few comments, what do you think?

2023-10-16 18:31 UTC, origranot commented on apps/frontend/src/routes/index.tsx
> +                  <img class="mx-auto my-8" style={logoStyle} width="410" height="73" src="logo.svg" alt="Logo" />{' '}
```{' '}``` Why do you need this?

2023-10-19 18:10 UTC, siddharth9300 commented on apps/frontend/src/routes/index.tsx
> +  };
@origranot done👍

2023-10-19 19:18 UTC, merged