fixed broken link
origranot/reduced.to pull request #514
Opened 2023-10-14 15:38 UTC by barkhaaroraa

fixes #465

2023-10-15 09:32 UTC, barkhaaroraa commented
@origranot could you please review and merge this

2023-10-15 18:30 UTC, origranot commented
@barkhaaroraa Hey,
I think it should redirect to the specific .MD file inside the docs app.

2023-10-16 18:33 UTC, origranot requested changes
@barkhaaroraa
It looks like the editUrl is wrong, please test it locally before opening a PR.

2023-10-16 18:33 UTC, origranot commented on apps/docs/docusaurus.config.js
> +          editUrl: 'https://github.com/origranot/reduced.to',
Hey @barkhaaroraa,
editUrl is wrong, take a look at: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs

2023-10-23 09:39 UTC, closed without merging