Update README.md
origranot/reduced.to pull request #527
Opened 2023-10-21 13:26 UTC by YadlaMani

Fixed Typos

2023-10-21 15:10 UTC, origranot commented
I think this can fit better:
```"Reduced.to is a modern web application that shortens the length of link URLs, making it easier to remember, share, and track."```

2023-10-21 15:11 UTC, origranot commented on README.md
> +    Reduced.to is a modern web application that reduces the length of the link URL. So it's easier to remember, share and track.
I think this is a better explanation:

```suggestion
Reduced.to is a modern web application that shortens the length of link URLs, making it easier to remember, share, and track.
```

2023-10-21 15:11 UTC, origranot requested changes
@YadlaMani Thank you for your contribution, please take a look at my suggestion.

2023-10-22 01:40 UTC, YadlaMani commented
@origranot do you want me to do this changes and commit

2023-10-23 18:58 UTC, origranot commented
@YadlaMani Yea 💯

2023-10-25 13:57 UTC, origranot commented
@YadlaMani Hey, 
Are you planing on push the changes?

2023-10-25 14:20 UTC, origranot commented
> Yeah

Ok, I will wait for you to resolve the comment I left.

2023-11-22 09:44 UTC, closed without merging