Feature : Enforce user to accept privacy policies
origranot/reduced.to pull request #540
Opened 2023-10-24 12:18 UTC by icepick4

Hey,

I added a checkbox for the privacy policies, now the user must check it to register.

Squash my commits I made some shitty commits.

2023-10-24 12:19 UTC, icepick4 commented
Fixes issue #529

2023-10-24 12:58 UTC, icepick4 commented
![image](https://github.com/origranot/reduced.to/assets/82316285/1d0b4655-d350-4a17-bb93-ac04c3f59986)
![image](https://github.com/origranot/reduced.to/assets/82316285/6b401940-471f-441f-9ad6-b6a5fdafd4d1)

2023-10-25 14:11 UTC, origranot commented on apps/frontend/src/routes/register/index.tsx
> +                        I agree with the <a href="/privacy-policy" class="text-accent">Privacy Policy</a>.
Please change the class into `text-primary`

2023-10-25 14:12 UTC, origranot commented on apps/frontend/src/routes/register/index.tsx
> +                    {action.value?.fieldErrors?.policies}
You don't need to use the optional chaining here.
```suggestion
                    {action.value.fieldErrors.policies}
```

2023-10-25 14:13 UTC, origranot requested changes
@icepick4 Hey,

I really liked it, nice job!!
I left a few comments, please review them 💯 

Let's merge it 🚀

2023-10-25 14:41 UTC, origranot commented on apps/frontend/src/routes/register/index.tsx
> +                        I agree with the <a href="/privacy-policy" class="text-accent">Privacy Policy</a>.
Maybe it worth open the link in a new tab?

2023-10-26 16:42 UTC, merged