chore: enhance documentation
origranot/reduced.to pull request #548
Opened 2023-10-25 17:52 UTC by singodiyashubham87

Fixes #536 

I've made the necessary changes in the markdown file, Now there will be bullet points instead of long paragraphs.

2023-10-27 14:02 UTC, origranot commented on apps/docs/docs/overview.md
> +* There is also a dashboard for registered users to view their shortened URLs and track their performance.
Consider change the text according to my suggestion.

```suggestion
* User pastes a long URL in the input field.
* Clicks "Shorten" button.
* The app creates a shorter URL.
* User can copy and share it.
* Clicking the short URL redirects to the long one.
* Registered users access a dashboard to track their links.
```

2023-10-27 14:03 UTC, origranot requested changes
@singodiyashubham87 Please take a look at my suggestion and commnet.
Also I noticed the CI workflow has failed.

2023-10-27 14:41 UTC, singodiyashubham87 commented
@origranot I've no idea why is this check failing, Can you please guide me?

2023-10-27 19:27 UTC, iamjatinchauhan commented
@singodiyashubham87 Try removing extra spaces from end of each point and replace * with - for order list.

2023-10-27 19:29 UTC, singodiyashubham87 commented
@iamjatinchauhan Thanks for your assistance, Appreciate it!

2023-10-27 19:33 UTC, singodiyashubham87 commented
@origranot All checks have been passed, Kindly merge the PR.

2023-10-30 14:30 UTC, singodiyashubham87 commented
@origranot Please merge this PR.

2023-11-11 09:49 UTC, closed without merging