fix: bug in dashboard page width when link is too long
origranot/reduced.to pull request #624
Opened 2023-12-19 21:17 UTC by essofyany

I there
here is a preview of the final result
![Capture d’écran du 2023-12-19 22-15-28](https://github.com/origranot/reduced.to/assets/62668827/9056552d-1e35-4946-ac5a-972fe61bb1d5)

2023-12-21 20:19 UTC, origranot commented
This looks great!

What I had in my mind was to limit the visual url, subtract and show only the first 20/30~ characters of a link, we could add dots (...) to the suffix of the subtracted link.
In addition we could create a tooltip when hovering the subtracted link.

Your solution is great, however when you have multiple rows the height of each row is not fixed.
What do you think?

2023-12-21 21:04 UTC, essofyany commented
Hello @origranot,

Great news! The adjustment ensures uniform row height, enhancing the table's overall cleanliness.

I attempted to integrate a tooltip, and the outcome is visible in the screenshot below:
![Screenshot](https://github.com/origranot/reduced.to/assets/62668827/c52bc94d-c630-491e-a65b-74239f4ccbef)

However, I've noticed that for extremely long URLs, the tooltip expands proportionally, making it as extensive as the URL itself. This might impact the visual appeal. Any suggestions on how to manage this scenario would be appreciated.

2023-12-21 21:45 UTC, origranot commented
> Hello @origranot,
> 
> Great news! The adjustment ensures uniform row height, enhancing the table's overall cleanliness.
> 
> I attempted to integrate a tooltip, and the outcome is visible in the screenshot below: ![Screenshot](https://private-user-images.githubusercontent.com/62668827/292317982-c52bc94d-c630-491e-a65b-74239f4ccbef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTUzNjYsIm5iZiI6MTcwMzE5NTA2NiwicGF0aCI6Ii82MjY2ODgyNy8yOTIzMTc5ODItYzUyYmM5NGQtYzYzMC00OTFlLWE2NWItNzQyMzlmNGNjYmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDIxNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlOWE4YWYwOWQxZGZlOWRkZjQzZjVlNTRkNzM2N2I3NGZlMjhkMjVkZGQ1NDEzMTYzMDc3ZmIyNmYyOGJhYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FYsNZrqNyymo9VXfrVpvW1bus87-Ntu3z7x9SBhgJvM)
> 
> However, I've noticed that for extremely long URLs, the tooltip expands proportionally, making it as extensive as the URL itself. This might impact the visual appeal. Any suggestions on how to manage this scenario would be appreciated.

This looks amazing!
I think we should allow more characters on the link itself, maybe extend in more 20/30 characters?
About the tooltip, I think we should use the same strategy. (most of the links won't be that long)
Keep in mind to support both light and dark mode 💯

2023-12-22 12:35 UTC, essofyany commented
Hi @origranot,

Here are the results of my changes. The dark theme is already handled by DaisyUI.

![Capture d’écran du 2023-12-22 13-23-09](https://github.com/origranot/reduced.to/assets/62668827/a2e2f176-81b1-4c4d-b437-9ae43468ed38)
![Capture d’écran du 2023-12-22 13-29-36](https://github.com/origranot/reduced.to/assets/62668827/bc7285f0-aace-4dd1-8b16-1b944b4d4705)

I limited the link text in table column to 30 characters and the tooltip text to 150.
should we add tooltip to **Shortened URL** or we keep the tooltip for the long URL only?

2023-12-23 08:01 UTC, origranot commented on apps/frontend/src/routes/dashboard/index.tsx
> +        const link = (limit: number) => (value.length > limit ? value.slice(0, limit) + '...' : value);
Consider change the function name to be more accurate.
How about `limitLink`?

2023-12-23 08:02 UTC, origranot requested changes
Hey @essofyany,
This looks great, consider change the function name 💯

2023-12-23 09:38 UTC, origranot approved these changes
Nice!

2023-12-23 09:38 UTC, merged